# Generated by Django 6.1.1 on 2026-09-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_statushistory_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('big_van', 'مركلة (كبيرة)'), ('van', 'مركبة'), ('moto', 'موتوسيكل (خفيف)')], max_length=20, null=True),
        ),
    ]
